### ISSUE TITLE
Clicking on an URL inside the detail view opens a wrong address inside the same window

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-creative-industries#10]
These are three problems:

1. It does not open the link in a separate window
2. It concatenates the link to the existing base URL
3. Some links that have an associated protocol do not open at all, example: `http://www.kunstmeranoarte.org/`

For example:
`www.zukunvt.com` becomes `https://webcomponents.opendatahub.bz.it/webcomponent/www.zukunvt.com`

**Comment by lelebus** [comment]
I do not have issues in opening links with the associated protocol.

Regarding the other links: to make them reachable, they need to have an associated protocol. We have to decide if every entry should have the specified protocol or if we should generating it from the component. Otherwise, inserted links would be opened as relative path.

**Comment by Piiit** [comment]
We need to default to https, if the protocol is missing and always open it in another window... opening it as relative paths is no option and should be avoided also if the given links from the API are wrong or incomplete

**Comment by Piiit** [comment]
@lelebus @ohnewein Solved in v0.8.0

**Comment by ohnewein** [comment]
I am still getting the error message in my Firefox .

![Screenshot from 2020-05-13 17-57-33](https://user-images.githubusercontent.com/414797/81836092-4f0fbb80-9543-11ea-8eb0-9df62b26ce4c.png)

**Comment by Piiit** [comment]
I have overseen that clicking on socials is still not solved yet, just tried webpages of companies

**Comment by Piiit** [comment]
@ohnewein Could you please describe which item you open, and what you do exactly to get this error? That would help @lelebus to track the bug easier.

**Comment by Piiit** [comment]
@lelebus If you click on linkedin icons, it does not open it in a new window. That is the bug, shown by Patrick's screenshot

**Comment by Piiit** [comment]
@lelebus  Strange new issue in v0.8.1
It always adds the webpage of the company to the linkedin link.

For example:
webpage = `www.christianschwienbacher.it`
linkedin = `https://www.christianschwienbacher.it/kontakt.html&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fchristian-schwienbacher-1b8959124`

**Comment by Piiit** [comment]
@lelebus It works now... some links are broken and some need login, like some from linkedin, but those come directly from the API. So the error must be solved by the editors of the spreadsheet...

One thing thou, if the protocol is given from the API for company webpages, we should not overwrite it. For example: 

https://www.hubertkostner.info/ does not work, but the API gives http://www.hubertkostner.info/

**Comment by Piiit** [comment]
@ohnewein This seems to be fixed now with version 0.8.4 please test again

**Comment by ohnewein** [comment]
Seams to work now!

**Comment by Piiit** [comment]
Perfect, closing it then
